name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  font_awesome_flutter: ^10.7.0
  flutter_localizations:
    sdk: flutter

  # ------------------------
  # State Management
  # ------------------------
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.0

  # ------------------------
  # UI / Responsiveness
  # ------------------------
  flutter_screenutil: ^5.9.0

  # ------------------------
  # Networking
  # ------------------------
  dio: ^5.7.0

  # ------------------------
  # Local Storage
  # ------------------------
  path_provider: ^2.1.2
  shared_preferences: ^2.3.2

  # ------------------------
  # Environment & Config
  # ------------------------
  flutter_dotenv: ^5.1.0

  # ------------------------
  # Utils
  # ------------------------
  equatable: ^2.0.5
  image_picker: ^1.2.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  google_maps_flutter: ^2.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/
    - assets/images/
    - assets/images/pin_verde.png
    - assets/images/pin_morado.png
    - assets/images/Citydriver-rafiki.png
    - assets/images/
